FROM node:lts-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH 
RUN npm install @vue/cli@5.0.8 -g
RUN npm install md-editor-v3
COPY package.json . 
COPY package-lock.json .
COPY /src .
RUN npm install


CMD ["npm", "run", "serve"]
